


josmith.org: 2015-01-01 04:09:19 [initialization] application restarted
josmith.org: 2015-01-01 04:09:19 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-01 04:09:19 [access] ip: 180.76.6.56, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-01 16:57:55 [initialization] application restarted
josmith.org: 2015-01-01 16:57:55 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-02 12:11:42 [initialization] application restarted
josmith.org: 2015-01-02 12:11:43 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-02 14:23:21 [initialization] application restarted
josmith.org: 2015-01-02 14:23:21 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-02 14:23:22 [access] ip: 62.210.83.26, browser --> www.josmith.org/
josmith.org: 2015-01-02 14:23:22 [access] ip: 62.210.83.26, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-02 18:43:15 [initialization] application restarted
josmith.org: 2015-01-02 18:43:15 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-02 18:43:17 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-02 18:43:22 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-03 06:40:47 [initialization] application restarted
josmith.org: 2015-01-03 06:40:47 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-03 06:40:47 [access] ip: 62.210.222.111, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-03 06:40:47 [access] ip: 62.210.222.111, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-03 06:40:47 [access] ip: 62.210.222.111, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-03 06:40:47 [access] ip: 62.210.222.111, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-03 06:40:47 [access] ip: 62.210.222.111, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-03 06:40:47 [access] ip: 62.210.222.111, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-03 06:54:13 [access] ip: 62.210.222.111, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-03 06:54:13 [access] ip: 62.210.222.111, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-03 06:54:13 [access] ip: 62.210.222.111, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-03 06:54:13 [access] ip: 62.210.222.111, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-03 06:54:14 [access] ip: 62.210.222.111, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-03 06:54:15 [access] ip: 62.210.222.111, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html



josmith.org: 2015-01-03 15:38:28 [initialization] application restarted
josmith.org: 2015-01-03 15:38:28 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-03 15:38:28 [access] ip: 180.76.5.76, browser --> www.josmith.org/
josmith.org: 2015-01-03 15:38:30 [access] ip: 180.76.5.167, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-04 01:51:47 [initialization] application restarted
josmith.org: 2015-01-04 01:51:47 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-04 01:52:09 [access] ip: 81.52.143.30, browser --> www.josmith.org/
josmith.org: 2015-01-04 01:52:49 [access] ip: 81.52.143.30, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-04 09:42:18 [initialization] application restarted
josmith.org: 2015-01-04 09:42:18 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-04 10:38:12 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-04 10:38:16 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-04 12:33:43 [initialization] application restarted
josmith.org: 2015-01-04 12:33:43 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-04 12:33:43 [access] ip: 66.249.64.50, browser --> www.josmith.org/



josmith.org: 2015-01-04 15:20:56 [initialization] application restarted
josmith.org: 2015-01-04 15:20:56 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-05 02:02:14 [initialization] application restarted
josmith.org: 2015-01-05 02:02:14 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-05 02:02:14 [access] ip: 64.246.161.42, http://whois.domaintools.com/josmith.org --> www.josmith.org/



josmith.org: 2015-01-05 08:19:45 [initialization] application restarted
josmith.org: 2015-01-05 08:19:45 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-05 08:19:49 [access] ip: 185.10.104.131, browser --> www.josmith.org/
josmith.org: 2015-01-05 08:19:53 [access] ip: 185.10.104.196, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-05 18:12:14 [initialization] application restarted
josmith.org: 2015-01-05 18:12:14 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-05 18:12:14 [access] ip: 195.154.181.160, http://www.josmith.org --> www.josmith.org/
josmith.org: 2015-01-05 18:39:15 [access] ip: 54.154.150.146, browser --> www.josmith.org/



josmith.org: 2015-01-06 02:53:02 [initialization] application restarted
josmith.org: 2015-01-06 02:53:02 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-06 02:53:02 [access] ip: 50.31.96.9, http://www.josmith.org --> www.josmith.org/
josmith.org: 2015-01-06 02:53:03 [access] ip: 50.31.96.9, browser --> www.josmith.org/
josmith.org: 2015-01-06 02:53:03 [access] ip: 50.31.96.9, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 02:53:03 [access] ip: 50.31.96.9, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 02:53:03 [access] ip: 50.31.96.9, http://www.josmith.org/contactdata.html --> www.josmith.org/contactdata.html
josmith.org: 2015-01-06 02:53:04 [access] ip: 50.31.96.9, browser --> www.josmith.org/contactdata.html



josmith.org: 2015-01-06 10:24:13 [initialization] application restarted
josmith.org: 2015-01-06 10:24:13 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-06 10:24:14 [access] ip: 69.58.178.56, browser --> www.josmith.org/
josmith.org: 2015-01-06 10:24:17 [access] ip: 69.58.178.56, browser --> m.josmith.org/
josmith.org: 2015-01-06 10:24:20 [access] ip: 69.58.178.56, browser --> www.josmith.org/contactdata.html
josmith.org: 2015-01-06 10:24:21 [access] ip: 69.58.178.56, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-06 18:40:53 [initialization] application restarted
josmith.org: 2015-01-06 18:40:53 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-06 18:40:53 [access] ip: 195.154.178.134, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-06 18:40:53 [access] ip: 195.154.178.134, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 18:40:53 [access] ip: 195.154.178.134, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-06 18:40:53 [access] ip: 195.154.178.134, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 18:40:53 [access] ip: 195.154.178.134, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-06 18:40:53 [access] ip: 195.154.178.134, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 18:54:30 [access] ip: 195.154.178.134, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-06 18:54:30 [access] ip: 195.154.178.134, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 18:54:32 [access] ip: 195.154.178.134, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-06 18:54:32 [access] ip: 195.154.178.134, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html
josmith.org: 2015-01-06 18:54:33 [access] ip: 195.154.178.134, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-06 18:54:33 [access] ip: 195.154.178.134, http://www.josmith.org/introduction.html --> www.josmith.org/introduction.html



josmith.org: 2015-01-07 06:28:09 [initialization] application restarted
josmith.org: 2015-01-07 06:28:09 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-07 06:28:14 [access] ip: 162.243.217.240, browser --> www.josmith.org/



josmith.org: 2015-01-07 08:57:16 [initialization] application restarted
josmith.org: 2015-01-07 08:57:16 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-07 08:57:16 [access] ip: 66.249.64.58, browser --> www.josmith.org/
josmith.org: 2015-01-07 09:06:02 [access] ip: 66.249.64.58, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-07 12:59:34 [initialization] application restarted
josmith.org: 2015-01-07 12:59:34 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-07 12:59:34 [access] ip: 66.249.64.58, browser --> www.josmith.org/
josmith.org: 2015-01-07 13:02:11 [access] ip: 66.249.64.54, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-07 18:33:11 [access] ip: 66.249.64.54, browser --> www.josmith.org/



josmith.org: 2015-01-07 22:16:29 [initialization] application restarted
josmith.org: 2015-01-07 22:16:29 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-07 22:16:29 [access] ip: 66.249.64.54, browser --> www.josmith.org/



josmith.org: 2015-01-08 00:26:02 [initialization] application restarted
josmith.org: 2015-01-08 00:26:02 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-08 06:13:52 [initialization] application restarted
josmith.org: 2015-01-08 06:13:52 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-08 06:13:52 [access] ip: 180.76.5.190, browser --> www.josmith.org/
josmith.org: 2015-01-08 06:13:53 [access] ip: 180.76.5.150, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-08 11:12:48 [initialization] application restarted
josmith.org: 2015-01-08 11:12:48 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-08 11:12:48 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-08 12:30:38 [initialization] application restarted
josmith.org: 2015-01-08 12:30:38 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-08 12:30:38 [access] ip: 66.249.64.54, browser --> www.josmith.org/
josmith.org: 2015-01-08 12:32:30 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-08 13:20:36 [initialization] application restarted
josmith.org: 2015-01-08 13:20:36 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-08 13:20:36 [access] ip: 178.255.215.65, browser --> www.josmith.org/



josmith.org: 2015-01-08 14:39:01 [initialization] application restarted
josmith.org: 2015-01-08 14:39:01 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-08 14:39:04 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-08 14:39:08 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-08 14:39:27 [access] ip: 66.249.78.90, browser --> www.josmith.org/contactdata.html



josmith.org: 2015-01-08 16:20:47 [initialization] application restarted
josmith.org: 2015-01-08 16:20:47 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-08 22:12:43 [initialization] application restarted
josmith.org: 2015-01-08 22:12:43 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-08 22:12:43 [access] ip: 41.227.253.122, http://stackoverflow.com/questions/22739590/how-to-share-single-sqlite-connection-in-multi-threaded-python-application --> www.josmith.org/
josmith.org: 2015-01-08 22:12:43 [access] ip: 41.227.253.122, http://www.josmith.org/ --> www.josmith.org/introduction.html



josmith.org: 2015-01-09 03:04:36 [initialization] application restarted
josmith.org: 2015-01-09 03:04:36 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-09 03:04:36 [access] ip: 195.154.226.90, browser --> www.josmith.org/



josmith.org: 2015-01-09 08:24:49 [initialization] application restarted
josmith.org: 2015-01-09 08:24:49 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-09 08:24:49 [access] ip: 180.76.6.47, browser --> www.josmith.org/
josmith.org: 2015-01-09 08:24:50 [access] ip: 180.76.6.139, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-09 12:09:45 [initialization] application restarted
josmith.org: 2015-01-09 12:09:45 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-09 12:09:45 [access] ip: 145.24.243.240, browser --> www.josmith.org/
josmith.org: 2015-01-09 12:09:45 [access] ip: 145.24.243.240, http://www.josmith.org/ --> www.josmith.org/introduction.html



josmith.org: 2015-01-10 07:12:17 [initialization] application restarted
josmith.org: 2015-01-10 07:12:17 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-10 07:12:19 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-10 07:12:26 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-10 07:47:05 [access] ip: 66.249.64.58, browser --> www.josmith.org/contactdata.html



josmith.org: 2015-01-10 08:49:28 [initialization] application restarted
josmith.org: 2015-01-10 08:49:28 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-10 08:49:28 [access] ip: 66.249.64.50, browser --> www.josmith.org/



josmith.org: 2015-01-10 10:36:25 [initialization] application restarted
josmith.org: 2015-01-10 10:36:25 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-10 10:36:25 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-10 11:47:50 [initialization] application restarted
josmith.org: 2015-01-10 11:47:50 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-10 11:47:50 [access] ip: 66.249.64.54, browser --> www.josmith.org/contactdata.html
josmith.org: 2015-01-10 12:19:48 [access] ip: 66.249.64.58, browser --> www.josmith.org/
josmith.org: 2015-01-10 12:22:46 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-10 15:53:47 [initialization] application restarted
josmith.org: 2015-01-10 15:53:47 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-10 17:20:57 [initialization] application restarted
josmith.org: 2015-01-10 17:20:57 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-10 17:20:57 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-10 17:56:07 [access] ip: 46.229.164.115, browser --> www.josmith.org/
josmith.org: 2015-01-10 18:14:12 [access] ip: 66.249.64.54, browser --> www.josmith.org/
josmith.org: 2015-01-10 18:16:57 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-10 19:39:32 [initialization] application restarted
josmith.org: 2015-01-10 19:39:32 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-10 19:39:34 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-10 19:39:40 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-10 19:46:33 [access] ip: 66.249.64.50, browser --> www.josmith.org/contactdata.html



josmith.org: 2015-01-10 21:54:36 [initialization] application restarted
josmith.org: 2015-01-10 21:54:36 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-11 00:00:22 [initialization] application restarted
josmith.org: 2015-01-11 00:00:22 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-11 00:00:22 [access] ip: 66.249.64.50, browser --> www.josmith.org/



josmith.org: 2015-01-11 01:39:55 [initialization] application restarted
josmith.org: 2015-01-11 01:39:55 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-11 01:39:55 [access] ip: 82.231.53.39, http://forum.alwaysdata.com/viewtopic.php?id=4150 --> www.josmith.org/
josmith.org: 2015-01-11 01:39:56 [access] ip: 82.231.53.39, http://www.josmith.org/ --> www.josmith.org/introduction.html



josmith.org: 2015-01-11 02:11:48 [initialization] application restarted
josmith.org: 2015-01-11 02:11:48 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-11 02:11:48 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-11 20:47:15 [initialization] application restarted
josmith.org: 2015-01-11 20:47:15 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-11 20:49:49 [access] ip: 180.76.6.61, browser --> www.josmith.org/
josmith.org: 2015-01-11 20:49:50 [access] ip: 180.76.6.61, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-12 03:50:59 [initialization] application restarted
josmith.org: 2015-01-12 03:50:59 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-12 03:50:59 [access] ip: 104.130.192.107, browser --> www.josmith.org/



josmith.org: 2015-01-12 05:07:58 [initialization] application restarted
josmith.org: 2015-01-12 05:07:58 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-12 05:07:58 [access] ip: 173.49.24.118, browser --> www.josmith.org/
josmith.org: 2015-01-12 05:13:03 [access] ip: 173.49.24.118, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-12 07:09:49 [access] ip: 66.249.64.54, browser --> www.josmith.org/
josmith.org: 2015-01-12 07:17:56 [access] ip: 66.249.64.50, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-12 21:15:28 [initialization] application restarted
josmith.org: 2015-01-12 21:15:28 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-12 23:50:48 [initialization] application restarted
josmith.org: 2015-01-12 23:50:48 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-13 09:25:56 [initialization] application restarted
josmith.org: 2015-01-13 09:25:56 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-13 09:25:56 [access] ip: 180.76.5.150, browser --> www.josmith.org/
josmith.org: 2015-01-13 09:25:57 [access] ip: 180.76.5.67, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-13 22:13:33 [initialization] application restarted
josmith.org: 2015-01-13 22:13:33 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-13 22:13:33 [access] ip: 129.42.161.36, http://stackoverflow.com/questions/22739590/how-to-share-single-sqlite-connection-in-multi-threaded-python-application --> www.josmith.org/
josmith.org: 2015-01-13 22:13:34 [access] ip: 129.42.161.36, http://www.josmith.org/ --> www.josmith.org/introduction.html



josmith.org: 2015-01-14 20:23:23 [initialization] application restarted
josmith.org: 2015-01-14 20:23:23 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-14 20:23:23 [access] ip: 195.154.226.90, browser --> www.josmith.org/



josmith.org: 2015-01-15 02:05:47 [initialization] application restarted
josmith.org: 2015-01-15 02:05:47 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-15 02:05:49 [access] ip: 77.75.77.32, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-15 07:46:04 [initialization] application restarted
josmith.org: 2015-01-15 07:46:04 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-15 07:46:04 [access] ip: 209.213.104.25, browser --> www.josmith.org/Fckeditor/editor/filemanager/browser/default/connectors/test.html
josmith.org: 2015-01-15 07:46:05 [access] ip: 209.213.104.25, browser --> www.josmith.org/FCKeditor/editor/filemanager/connectors/test.html
josmith.org: 2015-01-15 07:46:05 [access] ip: 209.213.104.25, browser --> www.josmith.org/Admin/fckeditor/editor/filemanager/browser/default/connectors/test.html
josmith.org: 2015-01-15 07:46:06 [access] ip: 209.213.104.25, browser --> www.josmith.org/Admin/fCKeditor/editor/filemanager/connectors/test.html
josmith.org: 2015-01-15 07:46:06 [access] ip: 209.213.104.25, browser --> www.josmith.org/Editor/editor/filemanager/browser/default/connectors/test.html
josmith.org: 2015-01-15 07:46:06 [access] ip: 209.213.104.25, browser --> www.josmith.org/Editor/editor/filemanager/connectors/test.html



josmith.org: 2015-01-15 20:46:31 [initialization] application restarted
josmith.org: 2015-01-15 20:46:31 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-16 03:32:55 [initialization] application restarted
josmith.org: 2015-01-16 03:32:55 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-16 03:32:55 [access] ip: 180.76.6.64, browser --> www.josmith.org/
josmith.org: 2015-01-16 03:32:56 [access] ip: 180.76.6.232, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-16 13:44:29 [initialization] application restarted
josmith.org: 2015-01-16 13:44:30 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-16 13:44:30 [access] ip: 195.154.226.90, browser --> www.josmith.org/



josmith.org: 2015-01-16 17:10:19 [initialization] application restarted
josmith.org: 2015-01-16 17:10:19 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-16 17:10:19 [access] ip: 180.76.6.17, browser --> www.josmith.org/
josmith.org: 2015-01-16 17:10:20 [access] ip: 180.76.6.147, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-16 22:06:39 [initialization] application restarted
josmith.org: 2015-01-16 22:06:39 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-16 22:06:39 [access] ip: 69.197.186.210, browser --> www.josmith.org/admin/fckeditor/editor/filemanager/browser/default/connectors/test.html
josmith.org: 2015-01-16 22:06:40 [access] ip: 69.197.186.210, browser --> www.josmith.org/admin/fckeditor/editor/filemanager/browser/default/connectors/test.html



josmith.org: 2015-01-17 07:46:05 [initialization] application restarted
josmith.org: 2015-01-17 07:46:05 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-17 07:46:05 [access] ip: 192.99.107.226, browser --> www.josmith.org/



josmith.org: 2015-01-17 10:07:47 [initialization] application restarted
josmith.org: 2015-01-17 10:07:47 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-17 10:07:47 [access] ip: 148.251.11.211, browser --> www.JOSMITH.org/



josmith.org: 2015-01-18 00:31:54 [initialization] application restarted
josmith.org: 2015-01-18 00:31:54 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-18 00:31:54 [access] ip: 216.145.17.190, http://whois.domaintools.com/josmith.org --> www.josmith.org/



josmith.org: 2015-01-18 14:35:36 [initialization] application restarted
josmith.org: 2015-01-18 14:35:36 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-18 14:35:36 [access] ip: 195.154.226.90, browser --> www.josmith.org/



josmith.org: 2015-01-18 21:10:30 [initialization] application restarted
josmith.org: 2015-01-18 21:10:30 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-18 21:10:30 [access] ip: 66.249.64.58, browser --> www.josmith.org/



josmith.org: 2015-01-18 23:03:22 [initialization] application restarted
josmith.org: 2015-01-18 23:03:22 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-19 11:22:58 [initialization] application restarted
josmith.org: 2015-01-19 11:22:58 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-19 11:23:00 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-19 11:23:05 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-19 22:04:46 [initialization] application restarted
josmith.org: 2015-01-19 22:04:46 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-19 22:04:46 [access] ip: 1.171.50.99, browser --> www.josmith.org/



josmith.org: 2015-01-20 01:08:53 [initialization] application restarted
josmith.org: 2015-01-20 01:08:53 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-20 09:10:10 [initialization] application restarted
josmith.org: 2015-01-20 09:10:10 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-20 09:10:35 [access] ip: 180.76.5.24, browser --> www.josmith.org/
josmith.org: 2015-01-20 09:10:36 [access] ip: 180.76.5.66, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-20 19:50:08 [initialization] application restarted
josmith.org: 2015-01-20 19:50:08 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-20 19:50:10 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-20 19:50:18 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-21 05:18:16 [initialization] application restarted
josmith.org: 2015-01-21 05:18:16 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-21 05:18:21 [access] ip: 207.46.13.42, browser --> www.josmith.org/introduction.html
josmith.org: 2015-01-21 05:18:27 [access] ip: 157.55.39.161, browser --> www.josmith.org/



josmith.org: 2015-01-21 07:58:08 [initialization] application restarted
josmith.org: 2015-01-21 07:58:08 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-21 07:58:08 [access] ip: 180.76.5.60, browser --> www.josmith.org/
josmith.org: 2015-01-21 07:58:13 [access] ip: 180.76.5.22, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-21 12:33:55 [initialization] application restarted
josmith.org: 2015-01-21 12:33:55 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-21 19:26:30 [initialization] application restarted
josmith.org: 2015-01-21 19:26:30 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-22 00:24:28 [initialization] application restarted
josmith.org: 2015-01-22 00:24:28 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-22 00:24:28 [access] ip: 136.243.14.163, browser --> www.josmith.org/



josmith.org: 2015-01-22 09:52:34 [initialization] application restarted
josmith.org: 2015-01-22 09:52:34 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-22 09:52:34 [access] ip: 66.249.67.62, browser --> www.josmith.org/



josmith.org: 2015-01-22 14:25:14 [initialization] application restarted
josmith.org: 2015-01-22 14:25:14 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-22 16:08:14 [access] ip: 66.249.67.46, browser --> www.josmith.org/



josmith.org: 2015-01-22 21:20:18 [initialization] application restarted
josmith.org: 2015-01-22 21:20:18 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-22 21:20:18 [access] ip: 66.249.67.46, browser --> www.josmith.org/
josmith.org: 2015-01-22 22:30:19 [access] ip: 66.249.67.46, browser --> www.josmith.org/



josmith.org: 2015-01-23 00:35:57 [initialization] application restarted
josmith.org: 2015-01-23 00:35:57 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-23 06:27:32 [initialization] application restarted
josmith.org: 2015-01-23 06:27:32 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-23 06:27:32 [access] ip: 66.249.67.62, browser --> www.josmith.org/



josmith.org: 2015-01-23 12:20:25 [initialization] application restarted
josmith.org: 2015-01-23 12:20:25 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-23 12:20:25 [access] ip: 66.249.67.54, browser --> www.josmith.org/



josmith.org: 2015-01-23 17:11:09 [initialization] application restarted
josmith.org: 2015-01-23 17:11:09 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-23 17:11:09 [access] ip: 66.249.78.76, browser --> www.josmith.org/



josmith.org: 2015-01-23 22:46:45 [initialization] application restarted
josmith.org: 2015-01-23 22:46:45 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-23 22:46:45 [access] ip: 188.165.15.36, browser --> www.josmith.org/



josmith.org: 2015-01-24 01:04:43 [initialization] application restarted
josmith.org: 2015-01-24 01:04:43 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-24 02:25:42 [initialization] application restarted
josmith.org: 2015-01-24 02:25:42 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-24 02:25:42 [access] ip: 38.104.237.74, browser --> www.josmith.org/



josmith.org: 2015-01-24 04:53:23 [initialization] application restarted
josmith.org: 2015-01-24 04:53:23 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-24 07:40:05 [initialization] application restarted
josmith.org: 2015-01-24 07:40:05 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-24 08:46:03 [initialization] application restarted
josmith.org: 2015-01-24 08:46:03 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-24 08:46:08 [access] ip: 136.243.14.163, browser --> www.josmith.org/
josmith.org: 2015-01-24 08:46:13 [access] ip: 136.243.14.163, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-24 13:03:48 [initialization] application restarted
josmith.org: 2015-01-24 13:03:48 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-24 13:15:52 [access] ip: 180.76.5.59, browser --> www.josmith.org/
josmith.org: 2015-01-24 13:15:54 [access] ip: 180.76.6.21, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-24 14:14:05 [initialization] application restarted
josmith.org: 2015-01-24 14:14:05 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-24 17:39:22 [initialization] application restarted
josmith.org: 2015-01-24 17:39:22 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-24 17:39:24 [access] ip: 162.243.215.90, browser --> www.josmith.org/



josmith.org: 2015-01-24 20:49:30 [initialization] application restarted
josmith.org: 2015-01-24 20:49:30 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-24 22:09:02 [access] ip: 180.76.6.130, browser --> www.josmith.org/
josmith.org: 2015-01-24 22:09:04 [access] ip: 180.76.5.80, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-25 04:21:53 [initialization] application restarted
josmith.org: 2015-01-25 04:21:53 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-25 04:21:53 [access] ip: 107.23.45.196, http://www.josmith.org/ --> www.josmith.org/
josmith.org: 2015-01-25 04:38:32 [access] ip: 195.154.226.90, browser --> www.josmith.org/
josmith.org: 2015-01-25 04:42:38 [access] ip: 103.228.4.116, http://www.josmith.org/ --> www.josmith.org/



josmith.org: 2015-01-25 07:57:23 [initialization] application restarted
josmith.org: 2015-01-25 07:57:23 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-25 07:57:23 [access] ip: 180.76.4.50, browser --> www.josmith.org/



josmith.org: 2015-01-25 10:43:33 [initialization] application restarted
josmith.org: 2015-01-25 10:43:33 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-25 10:43:36 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-25 10:43:40 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-25 17:52:57 [initialization] application restarted
josmith.org: 2015-01-25 17:52:57 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-26 23:51:12 [initialization] application restarted
josmith.org: 2015-01-26 23:51:12 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-26 23:51:14 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-26 23:51:20 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-27 00:56:59 [initialization] application restarted
josmith.org: 2015-01-27 00:56:59 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-27 00:56:59 [access] ip: 195.154.226.90, browser --> www.josmith.org/



josmith.org: 2015-01-27 02:00:06 [initialization] application restarted
josmith.org: 2015-01-27 02:00:06 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-27 05:41:13 [initialization] application restarted
josmith.org: 2015-01-27 05:41:13 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-27 05:41:13 [access] ip: 192.99.107.136, browser --> www.josmith.org/



josmith.org: 2015-01-27 17:27:30 [initialization] application restarted
josmith.org: 2015-01-27 17:27:30 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-27 17:27:30 [access] ip: 36.228.235.13, browser --> www.josmith.org/



josmith.org: 2015-01-27 20:10:55 [initialization] application restarted
josmith.org: 2015-01-27 20:10:55 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-27 20:10:57 [access] ip: 5.255.253.231, browser --> www.josmith.org/
josmith.org: 2015-01-27 20:11:03 [access] ip: 5.255.253.231, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-28 05:30:56 [initialization] application restarted
josmith.org: 2015-01-28 05:30:56 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-28 05:31:20 [access] ip: 180.76.6.45, browser --> www.josmith.org/
josmith.org: 2015-01-28 05:31:21 [access] ip: 180.76.6.130, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-29 02:09:43 [initialization] application restarted
josmith.org: 2015-01-29 02:09:43 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-29 02:09:43 [access] ip: 180.76.5.193, browser --> www.josmith.org/
josmith.org: 2015-01-29 02:09:46 [access] ip: 180.76.6.140, browser --> www.josmith.org/introduction.html



josmith.org: 2015-01-29 11:06:00 [initialization] application restarted
josmith.org: 2015-01-29 11:06:00 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-29 18:41:24 [initialization] application restarted
josmith.org: 2015-01-29 18:41:24 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-29 18:41:24 [access] ip: 66.249.67.46, browser --> www.josmith.org/



josmith.org: 2015-01-29 22:54:31 [initialization] application restarted
josmith.org: 2015-01-29 22:54:31 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




josmith.org: 2015-01-30 13:22:09 [initialization] application restarted
josmith.org: 2015-01-30 13:22:09 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-30 13:22:09 [access] ip: 66.249.67.62, browser --> www.josmith.org/



josmith.org: 2015-01-30 16:26:45 [initialization] application restarted
josmith.org: 2015-01-30 16:26:45 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-30 16:26:45 [access] ip: 54.145.170.205, browser --> www.josmith.org/
josmith.org: 2015-01-30 16:26:45 [access] ip: 54.145.170.205, http://www.josmith.org/ --> www.josmith.org/introduction.html



josmith.org: 2015-01-30 20:16:46 [initialization] application restarted
josmith.org: 2015-01-30 20:16:46 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-30 20:16:46 [access] ip: 195.154.226.90, browser --> www.josmith.org/



josmith.org: 2015-01-31 01:27:02 [initialization] application restarted
josmith.org: 2015-01-31 01:27:02 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-31 01:27:02 [access] ip: 64.246.178.34, http://whois.domaintools.com/josmith.org --> www.josmith.org/



josmith.org: 2015-01-31 15:24:04 [initialization] application restarted
josmith.org: 2015-01-31 15:24:04 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-31 15:24:04 [access] ip: 66.249.78.90, browser --> www.josmith.org/



josmith.org: 2015-01-31 20:51:07 [initialization] application restarted
josmith.org: 2015-01-31 20:51:07 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "/home/sterlicht/josmith/josmithModules/db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "/home/sterlicht/josmith/josmithModules/db.py", line 22, in execute
    raise exception
  File "/home/sterlicht/josmith/josmithModules/db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

josmith.org: 2015-01-31 20:51:15 [access] ip: 207.46.13.56, browser --> www.josmith.org/
josmith.org: 2015-01-31 20:51:17 [access] ip: 199.30.25.126, http://www.josmith.org/ --> www.josmith.org/introduction.html
